#!/bin/bash -e 
#
# ==============================================================================
# PAQUETE: prometeo-abc
# ARCHIVO: postinst
# DESCRIPCIÓN: Aplicaciòn para aprender el abecedario en lengua de señas venezolana.
# COPYRIGHT:
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
#  (C) 2013 Homero S. Hernandez H. <hsh283@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="prometeo-abc"

case ${1} in

	configure)
	# Para cada usuario en /home/ ...
	for usuario in /home/*? ;
	do

		# Obteniendo sólo el nombre del usuario
		usuario_min=$(basename ${usuario})

		# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
		case  $(grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow) in

			'')
			
			;;

			*)
	
				if [ -f /usr/share/icons/Gnamon/apps/48/prometeo-abc.png ] \
					|| [ -f /usr/share/icons/Gnamon/apps/scalable/prometeo-abc.svg ]; then

					echo 'iconos instalados'
				else
					echo 'instalando iconos'
					mkdir -p /usr/share/icons/Gnamon/apps/48/
					mkdir -p /usr/share/icons/Gnamon/apps/scalable/	
					cp -r /usr/share/prometeo-abc/prometeo-abc.png /usr/share/icons/Gnamon/apps/48/
					cp -r /usr/share/prometeo-abc/prometeo-abc.svg /usr/share/icons/Gnamon/apps/scalable/
				fi
			;;
		esac

	done

	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)

		echo "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1

	;;

esac

#DEBHELPER#

exit 0
